openjfx/openjfx-docs

build.gradle
gradle.html

Modify Gradle instructions to use a plugin instead of internal APIs.
Fix for #6

Modify Gradle instructions to use a plugin instead of internal APIs.

---

build.gradle
gradle.html

Reformats the gradle docs to match the output of `gradle init --type java-application`

Gradle reformatting

---

css/gluon.css
install-javafx.html
js/gluon.js

Add tabbed interface for *nix and windows commands

---

gradle.html

Show how to set the JavaFX version with the JavaFX Plugin.

#60 Update Gradle for setting JavaFX version

---

gradle.html
install-java.html
js/gluon.js
modular.html

- Update JDK, update JavaFX plugin version

#71 Update docs to JavaFX 11.0.2

---

gradle.html
ide-eclipse.html
ide-intellij.html
ide-netbeans.html
install-javafx.html
js/gluon.js
maven.html
modular.html

and prevent error if js takes too long

#56 Don’t rely on js to add the GitHub link 

---

README.md
index.html
js/gluon.js
next-steps.html

Update documents to support JavaFX 13

Update to JavaFX 13

---

maven.html

#111 
Fixing maven dependency in the tutorial for javafx to run.

Add maven dependencies

---

js/gluon.js

Update docs to use the latest release version of the maven plugin

Update javafx-maven-plugin version to 0.0.4

---

index.html
js/gluon.js

Update to JavaFX 14 release

---

css/gluon.css
gradle.html
ide-eclipse.html
ide-intellij.html
ide-netbeans.html
index.html
install-java.html
install-javafx.html
introduction.html
js/gluon.js
maven.html
modular.html

This PR updates the text to make it generic. Phrases like `Getting Started with JavaFX 13` has been updated to only say `Getting Started with JavaFX`, which is more generic and sounds better.
Also, updates styling for few HTML elements.

Text and style updates

---

index.html
js/gluon.js
next-steps.html

Does the following changes:
* Updates the text on buttons
* Adds buttons to skip other IDEs
* Fix url to JFX Github repository

Miscellaneous changes to documentation

---

introduction.html

They are still far more detailed than this website.

Link to the old Oracle docs for JavaFX

---

ide-intellij.html

#183 Add details to open Maven window

---

maven.html

#190 Add information about Maven archetype

---

js/gluon.js

Bump versions

---

js/gluon.js

Bumps JavaFX version to latest release 18.0.2

Bump JavaFX version to 18.0.2

---

install-java.html
introduction.html
js/gluon.js

JavaFX 20 release

---

gradle.html
install-java.html
js/gluon.js

JavaFX 21 release

---

js/gluon.js

JavaFX 22.0.1 release

---

.gitignore
gradle.html
ide-eclipse.html
js/gluon.js
maven.html

JavaFX 24 release

---

introduction.html
js/gluon.js

JavaFX 24 needs min JDK 22 or later

Update JDK versions

---

maven.html

use maven archetype variable

---

gradle.html
js/gluon.js
maven.html

JavaFX 25 release
